### ISSUE TITLE
Filter selection doesn't reflect between filter page and eksplor list page

### ISSUE THREAD

**Issue by Kyald1412** [oddesa/Papah#61]
<img src="https://user-images.githubusercontent.com/20111162/128530860-1b7ac25f-5eb7-4f7d-90ba-ecb57339b85c.PNG" width="150" height="280"><img src="https://user-images.githubusercontent.com/20111162/128530873-650f4876-4d92-4535-afdd-e8828ca94494.PNG" width="150" height="280">

**Comment by oddesa** [comment]
solved
